### ISSUE TITLE
gem install fails on OS X 10.9.4

### ISSUE THREAD

**Issue by abstiles** [AXElements/accessibility_core#14]
Seems to build fine on 10.9.2, but not in 10.9.4. The output of `gem install accessibility_core` is as follows:

```
Building native extensions.  This could take a while...
ERROR:  Error installing accessibility_core:
        ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
compiling core.c
core.c:142:4: error: values of type 'AXError' should not be used as format arguments; add an explicit cast to 'int' instead [-Werror,-Wformat]
                 code
                 ^~~~
                 (int)
1 error generated.
make: *** [core.o] Error 1


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/accessibility_core-0.4.3 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/accessibility_core-0.4.3/ext/accessibility/core/gem_make.out
```
